# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

mod_version = 1.0.1
maven_group = com.eightsidedsquare
archives_base_name = angling

fabric_version=0.133.4+1.21.8
sodium_version=mc1.21.6-0.6.13
cca_version=7.0.0-beta.1
geckolib_version=5.2.2
